---
title: "Bike"
output: html_document
---
NAME: Nicolò Ghioldi

BADGE: 789879

NICKNAME: n.ghioldi

TEAM: hermani

ROUND: 1st

### References:
* esame di Statistica Multivariata (Lunardon)

### Models

* KNN

### Non-standard R packages


```{r startup, include = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = T, eval=T, message=F, warning=F, error=F, comment=NA, cache=F, R.options=list(width=220))
```

### R code to reproduce the last submission:

```{r}
#richiediamo le librerie necessarie
library(dplyr)
library(fasttime)
library(lubridate)
library(rpart)
library(caret)

#carichiamo i data set
train <- read.csv("99.csv", stringsAsFactors=T)
test <- read.csv("100.csv",  stringsAsFactors=F)
train$count = log1p(train$count)

train %>% 
  mutate(datetime = fastPOSIXct(datetime, "GMT")) %>% 
  mutate(hour = hour(datetime),
         month = month(datetime),
         year = year(datetime),
         wday = wday(datetime)) -> train

test %>% 
  mutate(datetime = fastPOSIXct(datetime, "GMT")) %>% 
  mutate(hour = hour(datetime),
         month = month(datetime),
         year = year(datetime),
         wday = wday(datetime)) -> test


#trasformiamo variabili in factor per il training set
train$season=factor(train$season)
train$year=factor(train$year)
train$holiday=factor(train$holiday)
train$workingday=factor(train$workingday)
train$weather=factor(train$weather)
train$month=factor(train$month)
train$wday=factor(train$wday)
train$hour=factor(train$hour)

#scriviamo i livelli per le variabili factor del training set
levels(train$season)<-c("Winter","Springer", "Summer", "Fall")
levels(train$year)<-c("2011","2012")
levels(train$month)<-c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
levels(train$holiday)<-c("Not holiday", "Holiday")
levels(train$wday)<-c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
levels(train$workingday)<-c("Weekend or holiday", "Workday")
levels(train$weather)<-c("Sereno", "Pioggia", "Maltempo","Bruttissimo")

#applichiamo la stessa procedura per il test set
test$season=factor(test$season)
test$year=factor(test$year)
test$holiday=factor(test$holiday)
test$workingday=factor(test$workingday)
test$weather=factor(test$weather)
test$month=factor(test$month)
test$wday=factor(test$wday)
test$hour=factor(test$hour)

levels(test$season)<-c("Winter","Springer", "Summer", "Fall")
levels(test$year)<-c("2011","2012")
levels(test$month)<-c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
levels(test$holiday)<-c("Not holiday", "Holiday")
levels(test$wday)<-c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
levels(test$workingday)<-c("Weekend or holiday", "Workday")
levels(test$weather)<-c("Sereno", "Pioggia", "Maltempo","Bruttissimo")

#Feature engineering & Binarization

#Creiamo la variabile giorno sia per il train che per il test set
train$giorno="weekend"
train$giorno[train$workingday=="Workday"]="lavoro"
train$giorno[train$holiday=="Holiday"]="vacanza"

test$giorno="weekend"
test$giorno[test$workingday=="Workday"]="lavoro"
test$giorno[test$holiday=="Holiday"]="vacanza"

#Effettuiamo una binarization sulla variabile giorno e la conseguente creazione delle variabili lavoro, weekend e vacanza sia per il train che per il test set. Questo ha lo scopo di capire meglio la disreibuzione dei giorni di lavoro, weekend e vacanza
train$lavoro[train$giorno=="lavoro"]=1
train$lavoro[train$giorno!="lavoro"]=0
train$weekend[train$giorno=="weekend"]=1
train$weekend[train$giorno!="weekend"]=0
train$vacanza[train$giorno=="vacanza"]=1
train$vacanza[train$giorno!="vacanza"]=0
train$vacanza=factor(train$vacanza)
train$lavoro=factor(train$lavoro)
train$weekend=factor(train$weekend)

test$lavoro[test$giorno=="lavoro"]=1
test$lavoro[test$giorno!="lavoro"]=0
test$weekend[test$giorno=="weekend"]=1
test$weekend[test$giorno!="weekend"]=0
test$vacanza[test$giorno=="vacanza"]=1
test$vacanza[test$giorno!="vacanza"]=0
test$vacanza=factor(test$vacanza)
test$lavoro=factor(test$lavoro)
test$weekend=factor(test$weekend)

#trasformiamo in factor la variabile giorno 
train$giorno=factor(train$giorno)
test$giorno=factor(test$giorno)

#sempre attraverso la binarization creiamo le variabili sereno, pioggia, maltempo e bruttissimo allo scopo di vedere com'è strutturata la variabile weather e di capire quali di esse discriminano meglio la variabile count 
train$Sereno[train$weather=="Sereno"]=1
train$Sereno[train$weather!="Sereno"]=0
train$Sereno=factor(train$Sereno)
train$Pioggia[train$weather=="Pioggia"]=1
train$Pioggia[train$weather!="Pioggia"]=0
train$Pioggia=factor(train$Pioggia)
train$Maltempo[train$weather=="Maltempo"]=1
train$Maltempo[train$weather!="Maltempo"]=0
train$Maltempo[train$weather=="Bruttissimo"]=1
train$Maltempo=factor(train$Maltempo)

test$Sereno[test$weather=="Sereno"]=1
test$Sereno[test$weather!="Sereno"]=0
test$Sereno=factor(test$Sereno)
test$Pioggia[test$weather=="Pioggia"]=1
test$Pioggia[test$weather!="Pioggia"]=0
test$Pioggia=factor(test$Pioggia)
test$Maltempo[test$weather=="Maltempo"]=1
test$Maltempo[test$weather!="Maltempo"]=0
test$Maltempo[test$weather=="Bruttissimo"]=1
test$Maltempo=factor(test$Maltempo)


#dalla variabile season creiamo le variabili Winter, Springer, Summer e Fall per capire meglio la distribuzione di count tra le stagioni
train$winter[train$season=="Winter"]=1
train$winter[train$season!="Winter"]=0
train$springer[train$season=="Springer"]=1
train$springer[train$season!="Springer"]=0
train$summer[train$season=="Summer"]=1
train$summer[train$season!="Summer"]=0
train$fall[train$season=="Fall"]=1
train$fall[train$season!="Fall"]=0

train$winter=factor(train$winter)
train$springer=factor(train$springer)
train$summer=factor(train$summer)
train$fall=factor(train$fall)


test$winter[test$season=="Winter"]=1
test$winter[test$season!="Winter"]=0
test$springer[test$season=="Springer"]=1
test$springer[test$season!="Springer"]=0
test$summer[test$season=="Summer"]=1
test$summer[test$season!="Summer"]=0
test$fall[test$season=="Fall"]=1
test$fall[test$season!="Fall"]=0

test$winter=factor(test$winter)
test$springer=factor(test$springer)
test$summer=factor(test$summer)
test$fall=factor(test$fall)


#applichiamo la standardizzazione delle variabili che necessitano tale trasformazione
pp_train <- preProcess(train[, -c(6,10,11,12,9)], method = c("center", "scale"))   
train2=predict(pp_train, newdata = train)
train2$count=train$count

#facciamo la medesima cosa sul test set
pp_test <- preProcess(test, method = c("center", "scale"))
test2=predict(pp_test, newdata = test)

#scriviamo le formula relativa alle variabili che vogliamo inserire nel modello
formula=count~lavoro+weekend+Sereno+Maltempo+hour+atemp+year+season

#impostiamo i training parameters del modello caret
ctrl <- trainControl(method ="repeatedcv",number = 10,repeats = 10)

#dopo varie prove abbiamo optato per un modello KNN

#knn
set.seed(123)
knn <- train(
  formula, train2,
  method = "knn",
  trControl=ctrl)
knn


yhat <- expm1(predict(knn, newdata=test2))
head(yhat)



```


